server:
  port: 10000

#eureka 配置
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
#      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      defaultZone: http://localhost:10000/eureka/
  server:
    eviction-interval-timer-in-ms: 5000

#  instance:
#    instance-id: ${eureka.instance.ip-address}:${server.port}
#    ip-address: 127.0.0.1
#    prefer-ip-address: true
spring:
  application:
     name: eurekaService
#开启安全认证与账号设置
#  security:
#    user:
#      name: user
#      password: 123
#  basic:
#    enabled: true

